# Generated by Django 2.0 on 2018-03-27 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Add To Cart',
                'ordering': ['shoe'],
            },
        ),
        migrations.CreateModel(
            name='CompanyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_image', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Company List',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'User List',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShoeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_image', models.URLField()),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('size', models.CharField(max_length=100)),
                ('company_banner', models.URLField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.CompanyList')),
            ],
            options={
                'verbose_name_plural': 'Shoes List',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='addtocart',
            name='shoe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.ShoeList'),
        ),
        migrations.AddField(
            model_name='addtocart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.Registration'),
        ),
    ]
