# Generated by Django 2.0 on 2018-03-27 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='shoelist',
            name='company_banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.CompanyBanner'),
        ),
    ]
