# Generated by Django 2.0 on 2018-03-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_auto_20180327_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
