# Generated by Django 2.0 on 2018-03-27 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_addtocart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
